// Oslo Beer Tracker — Seed Data
// Prices compiled from publicly reported data (meravoslo.no, pilsposten.com, routesnorth.com) — May 2025
// Coordinates are approximate for demo purposes.

export const NEIGHBORHOODS = [
  'Sentrum',
  'Grünerløkka',
  'Grønland',
  'Tøyen',
  'St. Hanshaugen',
  'Majorstuen',
  'Sagene',
  'Sofienberg',
  'Aker Brygge',
  'Bjørvika',
];

export const AMENITIES = [
  { id: 'utepils', label: 'Utepils', icon: 'sun' },
  { id: 'food', label: 'Food', icon: 'utensils' },
  { id: 'darts', label: 'Darts', icon: 'target' },
  { id: 'shuffleboard', label: 'Shuffleboard', icon: 'rows-3' },
  { id: 'pool', label: 'Pool', icon: 'circle-dot' },
  { id: 'student_discount', label: 'Student price', icon: 'graduation-cap' },
  { id: 'sports_tv', label: 'Sports on TV', icon: 'tv' },
];

// Venues — 24 real Oslo bars with reported prices
export const VENUES = [
  {
    id: 'doner-bros',
    name: 'Döner Bros',
    neighborhood: 'Sentrum',
    address: 'Torggata 24, 0183 Oslo',
    lat: 59.9165,
    lng: 10.7475,
    beer: { brand: 'Ringnes', volume: 0.4, price: 48 },
    happyHour: null,
    hours: 'Mon–Sun 11:00–23:00',
    amenities: ['food'],
    lastUpdated: '2025-03-12',
    blurb: 'Kebab joint with legendary cheap pints — one of the most consistent price leaders in Sentrum.',
  },
  {
    id: 'london-pub',
    name: 'London Pub',
    neighborhood: 'Sentrum',
    address: 'C.J. Hambros plass 5, 0164 Oslo',
    lat: 59.9143,
    lng: 10.7406,
    beer: { brand: 'Hansa', volume: 0.5, price: 88 },
    happyHour: { price: 48, volume: 0.5, until: '20:00', days: 'Mon–Sun' },
    hours: 'Mon–Sun 15:00–03:00',
    amenities: ['darts', 'sports_tv', 'food'],
    lastUpdated: '2025-04-01',
    blurb: 'Historic institution with a piano bar upstairs. Best happy hour in town — 48 kr a halvliter before 8pm.',
  },
  {
    id: 'heidis-bier-bar',
    name: 'Heidis Bier Bar',
    neighborhood: 'Sentrum',
    address: 'Karl Johans gate 10, 0154 Oslo',
    lat: 59.9109,
    lng: 10.7498,
    beer: { brand: 'Ringnes', volume: 0.4, price: 89 },
    happyHour: { price: 35, volume: 0.4, until: 'all evening', days: 'Thu' },
    hours: 'Mon–Sun 15:00–03:00',
    amenities: ['sports_tv', 'food'],
    lastUpdated: '2025-02-20',
    blurb: 'Bavarian après-ski energy. Thursdays are wild — 35 kr all night.',
  },
  {
    id: 'bar-royal',
    name: 'Bar Royal',
    neighborhood: 'Sentrum',
    address: 'Torggata 10, 0181 Oslo',
    lat: 59.9158,
    lng: 10.7472,
    beer: { brand: 'Ringnes', volume: 0.5, price: 69 },
    happyHour: { price: 59, volume: 0.5, until: '21:00', days: 'Mon–Sun' },
    hours: 'Mon–Sat 14:00–03:00, Sun 16:00–01:00',
    amenities: ['food', 'sports_tv'],
    lastUpdated: '2025-03-28',
    blurb: 'Torggata stalwart. Friendly staff, solid bargain, always a seat at the bar.',
  },
  {
    id: 'luna-park',
    name: 'Luna Park Bar',
    neighborhood: 'Sentrum',
    address: 'Akersgata 47, 0180 Oslo',
    lat: 59.9156,
    lng: 10.7435,
    beer: { brand: 'Hansa', volume: 0.5, price: 79 },
    happyHour: null,
    hours: 'Mon–Sat 15:00–03:00, closed Sun',
    amenities: ['food'],
    lastUpdated: '2025-03-02',
    blurb: 'Tucked off Grensen — musicians, students, activists. Low ceilings, cheap pils, zero pretension.',
  },
  {
    id: 'cafe-fiasco',
    name: 'Café Fiasco',
    neighborhood: 'Sentrum',
    address: 'Pløens gate 1, 0181 Oslo',
    lat: 59.9141,
    lng: 10.7488,
    beer: { brand: 'Ringnes', volume: 0.5, price: 92 },
    happyHour: null,
    hours: 'Mon–Sun 10:00–01:00',
    amenities: ['food', 'utepils'],
    lastUpdated: '2025-03-15',
    blurb: 'Red-awning corner spot near Galleri Oslo. Classic neighborhood café feel.',
  },
  {
    id: 'no-name',
    name: 'No Name',
    neighborhood: 'Sentrum',
    address: 'Nedre Slottsgate 8, 0157 Oslo',
    lat: 59.9107,
    lng: 10.7426,
    beer: { brand: 'Ringnes', volume: 0.5, price: 65 },
    happyHour: null,
    hours: 'Mon–Sat 16:00–02:00',
    amenities: ['food'],
    lastUpdated: '2025-03-22',
    blurb: 'Two-for-130 kr all day — the rare Oslo bar with a genuine value deal.',
  },
  {
    id: 'the-alchemist',
    name: 'The Alchemist',
    neighborhood: 'Sentrum',
    address: 'Youngstorget 6, 0181 Oslo',
    lat: 59.9144,
    lng: 10.7480,
    beer: { brand: 'Tap pilsner', volume: 0.4, price: 68 },
    happyHour: { price: 54, volume: 0.4, until: '21:00', days: 'Mon–Sun' },
    hours: 'Mon–Sat 15:00–03:00',
    amenities: ['utepils', 'food'],
    lastUpdated: '2025-04-05',
    blurb: 'Youngstorget mainstay with a sunny terrace. 54 kr before 9pm.',
  },
  {
    id: 'mastermind',
    name: 'Mastermind',
    neighborhood: 'Grønland',
    address: 'Grønland 12, 0188 Oslo',
    lat: 59.9130,
    lng: 10.7607,
    beer: { brand: 'Tap pilsner', volume: 0.4, price: 68 },
    happyHour: { price: 54, volume: 0.4, until: '21:00', days: 'Mon–Sun' },
    hours: 'Mon–Sat 14:00–03:00',
    amenities: ['darts', 'pool'],
    lastUpdated: '2025-03-30',
    blurb: 'Pool tables, cheap shots, the good kind of dive.',
  },
  {
    id: 'bydelskroa',
    name: 'Bydelskroa',
    neighborhood: 'Tøyen',
    address: 'Hagegata 22, 0653 Oslo',
    lat: 59.9162,
    lng: 10.7743,
    beer: { brand: 'Ringnes', volume: 0.5, price: 74 },
    happyHour: null,
    hours: 'Mon–Sat 12:00–01:30, Sun 13:00–22:00',
    amenities: ['food', 'sports_tv'],
    lastUpdated: '2025-02-28',
    blurb: 'Tøyen neighborhood pub — the cheap pint anchor of the east side.',
  },
  {
    id: 'bohemen-sportspub',
    name: 'Bohemen Sportspub',
    neighborhood: 'Grünerløkka',
    address: 'Markveien 56, 0550 Oslo',
    lat: 59.9230,
    lng: 10.7559,
    beer: { brand: 'Frydenlund', volume: 0.5, price: 96 },
    happyHour: null,
    hours: 'Mon–Sun 15:00–02:00',
    amenities: ['sports_tv', 'darts'],
    lastUpdated: '2025-03-20',
    blurb: 'Every match on every screen. A proper sports pub without the markup.',
  },
  {
    id: 'torggata-botaniske',
    name: 'Torggata Botaniske',
    neighborhood: 'Sentrum',
    address: 'Torggata 17B, 0183 Oslo',
    lat: 59.9159,
    lng: 10.7474,
    beer: { brand: 'Pilsner', volume: 0.5, price: 98 },
    happyHour: null,
    hours: 'Mon–Sat 17:00–01:30',
    amenities: ['food'],
    lastUpdated: '2025-03-10',
    blurb: 'Plant-filled cocktail bar — beer isn\'t the headline, but it\'s honestly priced.',
  },
  {
    id: 'cafe-stolen',
    name: 'Café Stolen',
    neighborhood: 'Grünerløkka',
    address: 'Helgesens gate 10, 0553 Oslo',
    lat: 59.9249,
    lng: 10.7611,
    beer: { brand: 'Hansa', volume: 0.5, price: 78 },
    happyHour: { price: 59, volume: 0.5, until: 'all day', days: 'Wed' },
    hours: 'Mon–Sun 12:00–01:00',
    amenities: ['utepils', 'food', 'student_discount'],
    lastUpdated: '2025-04-10',
    blurb: 'Chairs from every decade. Wednesdays 59 kr all day.',
  },
  {
    id: 'thorvalds',
    name: 'Thorvalds',
    neighborhood: 'Grünerløkka',
    address: 'Thorvald Meyers gate 56, 0552 Oslo',
    lat: 59.9249,
    lng: 10.7599,
    beer: { brand: 'Pilsner', volume: 0.4, price: 92 },
    happyHour: { price: 74, volume: 0.4, until: '20:00', days: 'Mon–Sun' },
    hours: 'Mon–Sat 15:00–02:00',
    amenities: ['utepils', 'food'],
    lastUpdated: '2025-03-25',
    blurb: 'Løkka classic with a sunny sidewalk spill-out.',
  },
  {
    id: 'radio-lokka',
    name: 'Radio Løkka',
    neighborhood: 'Grünerløkka',
    address: 'Nordre gate 20, 0551 Oslo',
    lat: 59.9233,
    lng: 10.7570,
    beer: { brand: 'Pilsner', volume: 0.4, price: 83 },
    happyHour: { price: 65, volume: 0.4, until: '20:00', days: 'Mon–Sun' },
    hours: 'Mon–Sun 16:00–02:00',
    amenities: ['utepils', 'food'],
    lastUpdated: '2025-04-12',
    blurb: 'Big terrace facing Birkelunden park. Three for 190 kr before 8pm.',
  },
  {
    id: 'alf-nabolagsbar',
    name: 'Alf Nabolagsbar',
    neighborhood: 'Sagene',
    address: 'Maridalsveien 140, 0461 Oslo',
    lat: 59.9352,
    lng: 10.7563,
    beer: { brand: 'Fredrikstad pilsner', volume: 0.4, price: 92 },
    happyHour: { price: 78, volume: 0.4, until: '20:00', days: 'Mon–Sun' },
    hours: 'Mon–Sun 16:00–01:00',
    amenities: ['utepils', 'food'],
    lastUpdated: '2025-03-18',
    blurb: 'Alexander Kiellands plass neighborhood bar — warm, well-worn, a local favorite.',
  },
  {
    id: 'pinpin',
    name: 'PinPin',
    neighborhood: 'Majorstuen',
    address: 'Hegdehaugsveien 22, 0352 Oslo',
    lat: 59.9209,
    lng: 10.7279,
    beer: { brand: 'Ringnes', volume: 0.4, price: 92 },
    happyHour: { price: 69, volume: 0.4, until: '18:00', days: 'Mon–Sun' },
    hours: 'Mon–Sun 15:00–01:00',
    amenities: ['utepils', 'food'],
    lastUpdated: '2025-03-14',
    blurb: 'Leafy Hegdehaugsveien terrace. Early-bird 69 kr is the move.',
  },
  {
    id: 'heim',
    name: 'Heim',
    neighborhood: 'St. Hanshaugen',
    address: 'Colletts gate 33, 0169 Oslo',
    lat: 59.9275,
    lng: 10.7414,
    beer: { brand: 'Tap pilsner', volume: 0.6, price: 86 },
    happyHour: null,
    hours: 'Mon–Sun 12:00–00:30',
    amenities: ['utepils', 'food', 'student_discount'],
    lastUpdated: '2025-02-15',
    blurb: 'Mountain-cabin energy. 0.6L for 86 kr Thu–Sat — excellent price-per-liter.',
  },
  {
    id: 'rebell',
    name: 'Rebell',
    neighborhood: 'Grünerløkka',
    address: 'Markveien 35, 0554 Oslo',
    lat: 59.9243,
    lng: 10.7582,
    beer: { brand: 'Ringnes', volume: 0.4, price: 59 },
    happyHour: null,
    hours: 'Mon–Sun 15:00–02:00',
    amenities: ['food', 'sports_tv'],
    lastUpdated: '2025-04-03',
    blurb: 'All-day 59 kr Ringnes, no clock-watching required.',
  },
  {
    id: 'fyrhuset-kuba',
    name: 'Fyrhuset Kuba',
    neighborhood: 'Grünerløkka',
    address: 'Brenneriveien 1, 0182 Oslo',
    lat: 59.9215,
    lng: 10.7562,
    beer: { brand: 'Pilsner', volume: 0.4, price: 94 },
    happyHour: null,
    hours: 'Mon–Sun 12:00–01:30',
    amenities: ['utepils', 'shuffleboard', 'food', 'student_discount'],
    lastUpdated: '2025-03-08',
    blurb: 'Akerselva riverside. Shuffleboards upstairs, sun on the deck, 79 kr for students.',
  },
  {
    id: 'cortado',
    name: 'Cortado Café & Bar',
    neighborhood: 'Sagene',
    address: 'Sandakerveien 56, 0477 Oslo',
    lat: 59.9408,
    lng: 10.7613,
    beer: { brand: 'Ringnes', volume: 0.5, price: 69 },
    happyHour: null,
    hours: 'Mon–Sat 08:00–00:00, Sun 10:00–22:00',
    amenities: ['utepils', 'food'],
    lastUpdated: '2025-03-26',
    blurb: 'Sandaker local — coffee by day, 69 kr halvliter by night.',
  },
  {
    id: 'under-brua',
    name: 'Under Brua',
    neighborhood: 'Grünerløkka',
    address: 'Nybrua 2, 0188 Oslo',
    lat: 59.9185,
    lng: 10.7607,
    beer: { brand: 'Pilsner', volume: 0.5, price: 69 },
    happyHour: null,
    hours: 'Mon–Sun 15:00–02:00',
    amenities: ['utepils', 'food'],
    lastUpdated: '2025-03-11',
    blurb: 'Literally under the bridge. Riverside seats, honest prices.',
  },
  {
    id: 'vippa',
    name: 'Vippa',
    neighborhood: 'Bjørvika',
    address: 'Akershusstranda 25, 0150 Oslo',
    lat: 59.9038,
    lng: 10.7403,
    beer: { brand: 'Isbjørn', volume: 0.4, price: 92 },
    happyHour: null,
    hours: 'Wed–Sun 16:00–23:00',
    amenities: ['utepils', 'food'],
    lastUpdated: '2025-04-08',
    blurb: 'Waterfront food hall with fjord views. Come for utepils, stay for the sunset.',
  },
  {
    id: 'tullins-cafe',
    name: 'Tullins Café',
    neighborhood: 'Sentrum',
    address: 'Tullins gate 2, 0166 Oslo',
    lat: 59.9182,
    lng: 10.7348,
    beer: { brand: 'Pilsner (mugge 1.5L)', volume: 1.5, price: 294 },
    happyHour: { price: 219, volume: 1.5, until: 'all day', days: 'Mon' },
    hours: 'Mon–Sun 11:00–01:30',
    amenities: ['utepils', 'food', 'student_discount'],
    lastUpdated: '2025-03-19',
    blurb: 'Order the mugge — a full 1.5L pitcher. Mondays it\'s 219 kr (73 kr/halvliter).',
  },
];

// Derived helpers
export const tierForPricePerLiter = (ppl) => {
  if (ppl < 160) return 'low';       // < 80 kr / 0.5L
  if (ppl < 200) return 'mid';       // 80–100 kr / 0.5L
  return 'high';                     // 100+ kr / 0.5L
};

export const computePricePerLiter = (v) => Math.round(v.beer.price / v.beer.volume);
export const computeHalfLiter = (v) => Math.round((v.beer.price / v.beer.volume) * 0.5);
